Merge in NetBSD HEAD as of 2008-07-24

diff --git a/HEAD_640/pkgsrc/x11/pixman/patches/patch-ae b/HEAD_640/pkgsrc/x11/pixman/patches/patch-ae
--- a/HEAD_640/pkgsrc/x11/pixman/patches/patch-ae
+++ b/HEAD_640/pkgsrc/x11/pixman/patches/patch-ae
@@ -1,8 +1,8 @@
-$NetBSD: patch-ae,v 1.3 2008/06/19 17:51:27 bjs Exp $
+$NetBSD: patch-ae,v 1.6 2008/07/18 19:03:32 bjs Exp $
 
---- configure.orig	2008-06-09 12:35:16.000000000 -0400
+--- configure.orig	2008-07-17 13:39:07.000000000 -0400
 +++ configure
-@@ -19770,6 +19770,7 @@ fi
+@@ -19773,6 +19773,7 @@ fi
  
  
  have_gcc4=no
@@ -10,7 +10,7 @@ $NetBSD: patch-ae,v 1.3 2008/06/19 17:51:27 bjs Exp $
  { echo "$as_me:$LINENO: checking for -fvisibility" >&5
  echo $ECHO_N "checking for -fvisibility... $ECHO_C" >&6; }
  cat >conftest.$ac_ext <<_ACEOF
-@@ -19807,7 +19808,7 @@ sed 's/^/| /' conftest.$ac_ext >&5
+@@ -19810,7 +19811,7 @@ sed 's/^/| /' conftest.$ac_ext >&5
  fi
  
  rm -f core conftest.err conftest.$ac_objext conftest.$ac_ext
@@ -19,3 +19,12 @@ $NetBSD: patch-ae,v 1.3 2008/06/19 17:51:27 bjs Exp $
  if test "x$have_gcc4" = "xyes"; then
     CFLAGS="$CFLAGS -fvisibility=hidden"
  fi
+@@ -20057,7 +20058,7 @@ fi
+ 
+ { echo "$as_me:$LINENO: result: $have_sse2_intrinsics" >&5
+ echo "${ECHO_T}$have_sse2_intrinsics" >&6; }
+-if test $enable_sse2 = yes && test $have_sse_intrinsics = no ; then
++if test $enable_sse2 = yes && test $have_sse2_intrinsics = no ; then
+    { { echo "$as_me:$LINENO: error: SSE2 intrinsics not detected" >&5
+ echo "$as_me: error: SSE2 intrinsics not detected" >&2;}
+    { (exit 1); exit 1; }; }
