NetBSD HEAD as of 2007-09-09

diff --git a/HEAD/pkgsrc/pkgtools/libnbcompat/files/configure b/HEAD/pkgsrc/pkgtools/libnbcompat/files/configure
--- a/HEAD/pkgsrc/pkgtools/libnbcompat/files/configure
+++ b/HEAD/pkgsrc/pkgtools/libnbcompat/files/configure
@@ -10415,8 +10415,7 @@ fi
 
 
 
-
-for ac_func in getpassphrase getpgrp memmove select dirfd
+for ac_func in getpassphrase getpgrp memmove select
 do
 as_ac_var=`echo "ac_cv_func_$ac_func" | $as_tr_sh`
 { echo "$as_me:$LINENO: checking for $ac_func" >&5
@@ -10759,6 +10758,7 @@ _ACEOF
 else
   :
 fi
+
 { echo "$as_me:$LINENO: checking for struct statfs.f_iosize" >&5
 echo $ECHO_N "checking for struct statfs.f_iosize... $ECHO_C" >&6; }
 if test "${ac_cv_member_struct_statfs_f_iosize+set}" = set; then
@@ -10864,7 +10864,6 @@ _ACEOF
 else
   :
 fi
-
 
 { echo "$as_me:$LINENO: checking for struct dirent.d_namlen" >&5
 echo $ECHO_N "checking for struct dirent.d_namlen... $ECHO_C" >&6; }
@@ -11133,6 +11132,79 @@ else
   :
 fi
 
+
+{ echo "$as_me:$LINENO: checking for dirfd" >&5
+echo $ECHO_N "checking for dirfd... $ECHO_C" >&6; }
+cat >conftest.$ac_ext <<_ACEOF
+/* confdefs.h.  */
+_ACEOF
+cat confdefs.h >>conftest.$ac_ext
+cat >>conftest.$ac_ext <<_ACEOF
+/* end confdefs.h.  */
+ #include <sys/types.h>
+    #if HAVE_DIRENT_H
+    # include <dirent.h>
+    #else
+    # define dirent direct
+    # if HAVE_SYS_NDIR_H
+    #  include <sys/ndir.h>
+    # endif
+    # if HAVE_SYS_DIR_H
+    #  include <sys/dir.h>
+    # endif
+    # if HAVE_NDIR_H
+    #  include <ndir.h>
+    # endif
+    #endif
+    int dummy_var;
+
+int
+main ()
+{
+ dummy_var = dirfd((DIR *)0)
+  ;
+  return 0;
+}
+_ACEOF
+rm -f conftest.$ac_objext conftest$ac_exeext
+if { (ac_try="$ac_link"
+case "(($ac_try" in
+  *\"* | *\`* | *\\*) ac_try_echo=\$ac_try;;
+  *) ac_try_echo=$ac_try;;
+esac
+eval "echo \"\$as_me:$LINENO: $ac_try_echo\"") >&5
+  (eval "$ac_link") 2>conftest.er1
+  ac_status=$?
+  grep -v '^ *+' conftest.er1 >conftest.err
+  rm -f conftest.er1
+  cat conftest.err >&5
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); } && {
+	 test -z "$ac_c_werror_flag" ||
+	 test ! -s conftest.err
+       } && test -s conftest$ac_exeext &&
+       $as_test_x conftest$ac_exeext; then
+
+	{ echo "$as_me:$LINENO: result: yes" >&5
+echo "${ECHO_T}yes" >&6; }
+
+cat >>confdefs.h <<\_ACEOF
+#define HAVE_DIRFD 1
+_ACEOF
+
+
+else
+  echo "$as_me: failed program was:" >&5
+sed 's/^/| /' conftest.$ac_ext >&5
+
+		{ echo "$as_me:$LINENO: result: no" >&5
+echo "${ECHO_T}no" >&6; }
+
+
+fi
+
+rm -f core conftest.err conftest.$ac_objext conftest_ipa8_conftest.oo \
+      conftest$ac_exeext conftest.$ac_ext
 
 if test $ac_cv_type_long_long = yes; then
 
