NetBSD HEAD as of 2009-05-27 w/ QNX diffs

diff --git a/HEAD_641/pkgsrc/bootstrap/bootstrap b/HEAD_641/pkgsrc/bootstrap/bootstrap
--- a/HEAD_641/pkgsrc/bootstrap/bootstrap
+++ b/HEAD_641/pkgsrc/bootstrap/bootstrap
@@ -1,6 +1,6 @@
 #! /bin/sh
 
-# $NetBSD: bootstrap,v 1.141 2009/02/05 18:53:03 joerg Exp $
+# $NetBSD: bootstrap,v 1.144 2009/04/23 00:15:53 minskim Exp $
 #
 #
 # Copyright (c) 2001-2002 Alistair G. Crooks.  All rights reserved.
@@ -282,14 +282,14 @@ mkdir_p()
 
 mkdir_p_early()
 {
-	if [ ! -d "$1" ]; then
-		if mkdir -p "$1"; then
-			:
-		else
-			echo_msg "mkdir $1 exited with status $?"
-			die "aborted."
-		fi
+	[ -d "$1" ] && return 0	
+	mkdir -p "$1" 2> /dev/null && return 0
+	mkdir_p_early `basename "$1"`
+	if [ ! -d "$1" ] && mkdir "$1"; then
+		echo_msg "mkdir $1 exited with status $?"
+		die "aborted."
 	fi
+	return 0
 }
 
 copy_src()
@@ -639,12 +639,6 @@ QNX)
 	;;
 esac
 
-if [ -z "$fetch_cmd" ]; then
-	need_ftp=yes
-else
-	need_ftp=no
-fi
-
 # If "--full" is specified, then install all of the platform-independent
 # bootstrap software.
 #
@@ -653,7 +647,6 @@ yes)
 	need_bsd_install=yes
 	need_awk=yes
 	need_sed=yes
-	need_ftp=yes
 	need_ksh=yes
 	;;
 esac
@@ -700,6 +693,11 @@ check_prog rmdirprog rmdir
 check_prog sedprog sed
 check_prog shprog sh
 check_prog whoamiprog whoami
+
+if [ -d "${wrkdir}" ] || [ -f "${wrkdir}" ]; then
+	echo "\"${wrkdir}\" already exists, please remove it or use --workdir.";
+	exit 1
+fi
 
 mkdir_p_early ${wrkdir}
 if touch ${wrkdir}/.writeable; then
