NetBSD HEAD as of 2010-12-19

diff --git a/vendor/HEAD/pkgsrc/bootstrap/bootstrap b/vendor/HEAD/pkgsrc/bootstrap/bootstrap
--- a/vendor/HEAD/pkgsrc/bootstrap/bootstrap
+++ b/vendor/HEAD/pkgsrc/bootstrap/bootstrap
@@ -1,6 +1,6 @@
 #! /bin/sh
 
-# $NetBSD: bootstrap,v 1.157 2010/03/19 14:11:11 seanb Exp $
+# $NetBSD: bootstrap,v 1.161 2010/11/20 00:49:33 obache Exp $
 #
 #
 # Copyright (c) 2001-2002 Alistair G. Crooks.  All rights reserved.
@@ -316,6 +316,7 @@ checkarg_sane_absolute_path() {
 	"")	;; # the default value will be used.
 	*[!-A-Za-z0-9_./]*)
 		die "ERROR: Invalid characters in path $1 (from $2)." ;;
+	*/)	die "ERROR: The argument to $2 must not end in /." ;;
 	/*)	;;
 	*)	die "ERROR: The argument to $2 must be an absolute path." ;;
 	esac
@@ -333,6 +334,15 @@ checkarg_sane_relative_path() {
 
 bootstrap_sh=${SH-/bin/sh}
 bootstrap_sh_set=${SH+set}
+
+case "$bootstrap_sh" in
+/*)
+	;;
+*)
+	echo "ERROR: The variable SH must contain an absolute path" 1>&2 
+	exit 1
+	;;
+esac
 
 # On some newer Ubuntu installations, /bin/sh is a symlink to /bin/dash,
 # whose echo(1) is not BSD-compatible.
